//! @file       clarity_config.h.in
//! @brief      Configuration for the clarity project
//!
//! @author     Jeffrey Wallace
//! @copyright  MIT

#pragma once

// CLarity Imports

// Standard Imports
#include <string>

// Third-Party Imports

namespace clarity {

    //! The path to the kernel directory - generated by cmake
    const std::string KERNEL_DIR = "/home/jwallace/lib/clarity/src/kernels";

}
